java_library(
  name = 'guava',
  visibility = ['PUBLIC'],
  exported_deps = [
    ':guava_jar'
  ],
)
prebuilt_jar(
  name = 'guava_jar',
  binary_jar = ':guava_remote_jar',
  deps = [
    '//buckbuild/jars/com/google/code/findbugs:jsr305',
  ],
  visibility = [
    'PUBLIC'
  ],
)
remote_file(
  out = 'guava.jar',
  name = 'guava_remote_jar',
  url = 'http://repo.maven.apache.org/maven2/com/google/guava/guava/19.0/guava-19.0.jar',
  sha1 = '6ce200f6b23222af3d8abb6b6459e6c44f4bb0e9',
)

