java_library(
    name = "util",
    srcs = glob([
        "**/*.java",
    ]),
    deps = [
        "//third_party:com_fasterxml_jackson_core_jackson_core",
        "//third_party:com_fasterxml_jackson_core_jackson_databind",
        "//third_party:com_fasterxml_jackson_core_jackson_annotations",
        "//third_party:org_apache_commons_commons_lang3",
        "//third_party:javax_ws_rs_javax_ws_rs_api",
    ],
    visibility = ["//visibility:public"],
)
