java_library(
    name = "jexl",
    srcs = glob([
        "**/*.java",
    ]),
    deps = [
      "//third_party:org_apache_commons_commons_jexl3",
      "//timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/rml",
      "//third_party:com_google_guava_guava",
      "//third_party:org_slf4j_slf4j_api",
      "//third_party:com_fasterxml_jackson_core_jackson_core",
      "//third_party:com_fasterxml_jackson_core_jackson_databind",
    ],
    visibility = ["//visibility:public"],
)
