= Timbuctoo

Bridge to networked research data

https://gitter.im/HuygensING/timbuctoo[image:https://badges.gitter.im/HuygensING/timbuctoo.svg[alt="Join the chat at https://gitter.im/HuygensING/timbuctoo"]]

//tag::support-note[]
[NOTE]
====
This software is developed and supported by the http://huygens.knaw.nl[Huygens Institute] in the Netherlands. 
We intend to support the software indefinitely, but *2018* is our current planning horizon.
This notice will be updated before the end of 2018 with the new support duration.

  * Support means that we'll review your https://github.com/huygensing/timbuctoo/pulls[pull requests], respond to https://github.com/huygensing/timbuctoo/issues[issues] and answer questions on the http://gitter.im/huygensing/timbuctoo[chat].
  * It does not mean that we'll fix every issue that you raise.
  * But it does mean that we'll commit regularly with new features or patches (usually every workday).
  * While we try to make timbuctoo run everywhere, we're actively running it on Redhat 6. Using it on other platforms may trigger bugs that we are not aware of (and that you should report!)
====
//end::support-note[]

== Background

//tag::background[]
Timbuctoo is aimed at historians doing interpretative research.
Such a researcher collects facts from various documents, interprets and structures them, and creates tables of these facts. 
The researcher then uses this new dataset either as an object to do analysis on, or as an index that allows them to look at their sources from a distance quickly stepping back to the original source for the real interpretative work.
 
As such an historian you often need to categorize your findings. 
For example: you keep track of birthplaces.
You then need to decide how to write down the birthplace

 - Do you use the name of the city, or the burrough? 
 - Do you use the current name or the name when the person was born?
 - If your dataset spans a long time you might have two different cities on the same geographical location. Are they one name or more?

These judgements are sometimes the core of your research and sometimes incidental to it.
Timbuctoo aims to make it easier to publish your research dataset and then to re-use other people's published datasets.
To continue the example: another researcher might create a dataset containing locations, their coördinates and names and how that changed over time. You can then re-use that dataset and link to the entries instead of typing a string of characters that a humand might correctly interpret or not.

There are database-like systems, so storing your data somewhere is easy.
However, there are not many tools that will:

 . allow you to upload any dataset without having to write code, (for most database importing large datasets will require you to write some amount of SQL, SPARQL or batch processing code) 
 . expose your dataset so that it can be retrieved by another researcher (a http download and a REST interface)
 . allow the researcher to base it's new dataset on that existing dataset 
  * with a provenance trail
  * without having to agree on the data model
  * without having to agree on all data contents
 . keep track of updates to the source dataset and allow the user to subscribe to these changes

Which is the added value timbuctoo will bring. 
//end::background[]

video::186090384[vimeo, width=640, height=355]

== License

Timbuctoo is licensed under the link:./LICENSE.txt[GPL license]

== Contributing

See the link:./CONTRIBUTING.adoc[contribution guidelines]

== Documentation

Read about compiling, installing/running and using/developing timbuctoo in the link:./documentation[documentation] folder.
A nicely rendered version of this documentation can be found http://huygensing.github.io/timbuctoo[online].

== Acknowledgements

Timbuctoo is funded by

 * The Huygens Institute (indefinite)
 * CLARIAH.nl (until ...)
 * NDE (funding ends december 2016)

'''

This repository is available online at https://github.com/HuygensING/timbuctoo
