java_library(
    name = "backupforstaging",
    srcs = glob([
        "**/*.java",
    ]),
    deps = [
      "//third_party:commons_io_commons_io",
    ],
    visibility = ["//visibility:public"],
)
