java_library(
  name = 'stax-api',
  visibility = ['PUBLIC'],
  exported_deps = [
    ':stax-api_jar'
  ],
)
prebuilt_jar(
  name = 'stax-api_jar',
  binary_jar = ':stax-api_remote_jar',
  deps = [
  ],
  visibility = [
    'PUBLIC'
  ],
)
remote_file(
  out = 'stax-api.jar',
  name = 'stax-api_remote_jar',
  url = 'http://repo.maven.apache.org/maven2/javax/xml/stream/stax-api/1.0-2/stax-api-1.0-2.jar',
  sha1 = 'd6337b0de8b25e53e81b922352fbea9f9f57ba0b',
)

