java_library(
  name = 'timbuctoo-instancev4',
  annotation_processors=['org.immutables.value.internal.$processor$.$Processor'],
  annotation_processor_deps=['//buckbuild/jars/org/immutables:value'],
  srcs = glob(['src/main/java/**/*.java'],
    [ #excludes
      'src/main/java/nl/knaw/huygens/timbuctoo/buck/**/*.java',
    ]
  ),
  resources = glob(['src/main/resources/**/*']),
  deps = [
    '//security-client-agnostic:security-client-agnostic',
    '//buckbuild/jars/org/immutables:value',
    "//buckbuild/jars/io/dropwizard:dropwizard-jetty",
    "//buckbuild/jars/org/codehaus/groovy:groovy-jsr223-indy",
    "//buckbuild/jars/org/codehaus/groovy:groovy-xml",
    "//buckbuild/jars/org/apache/ivy:ivy",
    "//buckbuild/jars/org/eclipse/jetty:jetty-util",
    "//buckbuild/jars/io/dropwizard/metrics:metrics-httpclient",
    "//buckbuild/jars/org/neo4j:neo4j-tinkerpop-api",
    "//buckbuild/jars/org/apache/poi:poi-ooxml-schemas",
    "//buckbuild/jars/commons-configuration:commons-configuration",
    "//buckbuild/jars/org/apache/xmlbeans:xmlbeans",
    "//buckbuild/jars/org/apache/commons:commons-lang3",
    "//buckbuild/jars/commons-lang:commons-lang",
    "//buckbuild/jars/org/glassfish/jersey/core:jersey-server",
    "//buckbuild/jars/io/dropwizard:dropwizard-assets",
    "//buckbuild/jars/io/dropwizard:dropwizard-client",
    "//buckbuild/jars/io/dropwizard:dropwizard-configuration",
    "//buckbuild/jars/io/dropwizard:dropwizard-forms",
    "//buckbuild/jars/com/google/code/findbugs:jsr305",
    "//buckbuild/jars/com/google/code/gson:gson",
    "//buckbuild/jars/org/hibernate:hibernate-validator",
    "//buckbuild/jars/org/apache/httpcomponents:httpcore",
    "//buckbuild/jars/io/dropwizard/metrics:metrics-core",
    "//buckbuild/jars/io/dropwizard/modules:dropwizard-java8",
    "//buckbuild/jars/org/neo4j:neo4j-tinkerpop-api-impl",
    "//buckbuild/jars/org/apache/poi:poi",
    "//buckbuild/jars/org/apache/tinkerpop:gremlin-groovy",
    "//buckbuild/jars/javax/validation:validation-api",
    "//buckbuild/jars/com/github/DANS-KNAW:dans-dp-lib",
  ],
  exported_deps = [
    "//buckbuild/jars/javax/annotation:javax.annotation-api",
    "//buckbuild/jars/com/fasterxml/jackson/core:jackson-annotations",
    "//buckbuild/jars/com/fasterxml/jackson/core:jackson-core",
    "//buckbuild/jars/com/fasterxml/jackson/core:jackson-databind",
    "//buckbuild/jars/org/glassfish/jersey/core:jersey-common",
    "//buckbuild/jars/com/kjetland/dropwizard:dropwizard-activemq",
    "//buckbuild/jars/io/dropwizard:dropwizard-core",
    "//buckbuild/jars/io/dropwizard:dropwizard-jersey",
    "//buckbuild/jars/io/dropwizard:dropwizard-lifecycle",
    "//buckbuild/jars/io/dropwizard:dropwizard-servlets",
    "//buckbuild/jars/com/google/guava:guava",
    "//buckbuild/jars/org/apache/httpcomponents:httpclient",
    "//buckbuild/jars/nl/knaw/huygens:huygens-persistence",
    "//buckbuild/jars/com/javaslang:javaslang",
    "//buckbuild/jars/org/apache/jena:jena-arq",
    "//buckbuild/jars/org/apache/jena:jena-core",
    "//buckbuild/jars/org/glassfish/jersey/media:jersey-media-multipart",
    "//buckbuild/jars/io/dropwizard/metrics:metrics-annotation",
    "//buckbuild/jars/io/dropwizard/metrics:metrics-healthchecks",
    "//buckbuild/jars/org/neo4j:neo4j-kernel",
    "//buckbuild/jars/org/apache/poi:poi-ooxml",
    "//buckbuild/jars/javax/ws/rs:javax.ws.rs-api",
    "//buckbuild/jars/org/slf4j:slf4j-api",
    "//buckbuild/jars/org/apache/tinkerpop:gremlin-core",
    "//buckbuild/jars/org/apache/tinkerpop:neo4j-gremlin",
    "//buckbuild/jars/xml-apis:xml-apis",
  ]
)

java_library(
  name = 'app-with-test-stubs',
  srcs = glob(
    [
      'src/test/java/**/*.java'
    ],
    excludes = [
      'src/test/java/**/*Test.java'
    ]
  ),
  deps = [
  ],
  exported_deps = [
    '//buckbuild/jars/org/mockito:mockito-core',
    '//timbuctoo-test-services:timbuctoo-test-services',
    '//buckbuild/jars/org/hamcrest:hamcrest-all',
    '//buckbuild/jars/org/neo4j:neo4j-tinkerpop-api',
    '//buckbuild/jars/org/neo4j:neo4j-tinkerpop-api-impl',
    '//buckbuild/jars/commons-configuration:commons-configuration',
    '//buckbuild/jars/org/neo4j:neo4j-kernel-tests',
    ':timbuctoo-instancev4',
    '//buckbuild/jars/com/google/code/gson:gson',
  ]
)

java_test(
  name = 'tests',
  srcs = glob(
    ['src/test/java/**/*Test.java'],
  ),
  resources = glob(['src/test/resources/**/*']),
  deps = [
    '//buckbuild/jars/org/mockito:mockito-core',
    "//buckbuild/jars/com/google/guava:guava",
    "//buckbuild/jars/junit:junit",
    '//buckbuild/jars/org/hamcrest:hamcrest-all',
    '//timbuctoo-test-services:timbuctoo-test-services',
    ':app-with-test-stubs',
    '//buckbuild/jars/org/apache/commons:commons-lang3',
    '//buckbuild/jars/org/apache/jena:jena-shaded-guava',
    '//buckbuild/jars/org/apache/poi:poi',
    '//buckbuild/jars/org/neo4j:neo4j-tinkerpop-api',
    '//security-client-agnostic:security-client-agnostic',
    "//buckbuild/jars/io/dropwizard:dropwizard-testing",
    "//buckbuild/jars/uk/co/datumedge:hamcrest-json",
  ],
  visibility = [
    "PUBLIC"
  ]
)
