#! /bin/sh
### BEGIN INIT INFO
# Provides:          skeleton
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.
### END INIT INFO

# Do NOT "set -e"

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="Handle Server"
NAME=hdl-server
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

# RedHat source functions
. /etc/rc.d/init.d/functions

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
. /lib/lsb/init-functions

# Read configuration variable file if it is present or exit
if [ ! -r /etc/default/$NAME ]; then
	echo "cannot find configuration"
fi
. /etc/default/$NAME

DAEMON=$HSJ_DIR/bin/hdl-server
DAEMON_ARGS=$SERVER_DIR
LOCKFILE="$SERVER_DIR/delete_this_to_stop_server"

#
# Function that starts the daemon/service
#
do_start()
{
	echo "Starting $DESC" "$NAME"
	# Exit if the package is not installed
	if [ ! -x "$DAEMON" ]; then
		echo "cannot execute $DAEMON"
		return 2
	fi

	if [ -f "$LOCKFILE" ]; then
		echo "Service already started"
		return 1;
	fi

	# code copied from hdl-server that is supplied by handle
	# Load all of the .jar files in the lib directory into the classpath
	CP=""
	for jarfile in $HSJ_DIR/lib/*.jar ; do
	  CP=${CP}:${jarfile}
	done
	for jarfile in $HSJ_DIR/lib/*/*.jar ; do
	  CP=${CP}:${jarfile}
	done
	for jarfile in $HSJ_DIR/{lib/amazons3/*.jar ; do
	  CP=${CP}:${jarfile}
	done
	
	logfile=/var/log/$NAME.log

	java -server -Xmx200M -cp "${CP}" net.handle.server.Main "$DAEMON_ARGS" >>  $logfile 2>&1 &
	
	return 0	
}

#
# Function that stops the daemon/service
#
do_stop(){
	echo "Stopping $DESC" "$NAME"
	if [ !  -f "$LOCKFILE" ]; then
		echo "Service not running"
		return 1;
	fi

	rm -f $LOCKFILE

	if [ -f "$LOCKFILE" ]; then
		echo "Service could not be stopped"
		return 1;
	fi

	return 0
}

case "$1" in
  start)
	do_start
	case "$?" in
		0) log_success_msg  ;;
		*) log_failure_msg  ;;
	esac
	;;
  stop)
	do_stop

	case "$?" in
		0) log_success_msg  ;;
		*) log_failure_msg  ;;
	esac
	;;
  status)
	if [ -f "$LOCKFILE" ]; then
		echo "Service is running"
		exit 0;
	else
		echo "Service is stopped"
		exit 0;
	fi
       ;;
  restart)
	echo  "Restarting $DESC" "$NAME"
	do_stop
	case "$?" in
                0) log_success_msg  ;;
                *) log_failure_msg  ;;
        esac	
	do_start
	case "$?" in
                0) log_success_msg  ;;
                *) log_failure_msg  ;;
        esac
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|status|restart}" >&2
	exit 3
	;;
esac

:
