java_library(
  name = 'timbuctoo-test-services',
  srcs = glob(['src/main/java/**/*.java']),
  deps = [
    "//buckbuild/jars/com/google/guava:guava",
    "//buckbuild/jars/org/hamcrest:hamcrest-all",
  ],
  exported_deps = [
  ],
  visibility = [
    "PUBLIC"
  ]
)
