java_library(
    name = "timbuctoo-test-services",
    srcs = glob([
      "src/main/java/**/*.java",
    ]),
    resources = glob([
      "src/main/resources/**/*",
    ]),
    deps = [
      "//third_party:com_google_guava_guava",
      "//third_party:org_hamcrest_hamcrest_all",
    ],
    visibility = ["//visibility:public"],
)
