java_library(
    name = "azureblob",
    srcs = glob([
        "**/*.java",
    ]),
    deps = [
      "//timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/backupforstaging",
      "//third_party:com_microsoft_azure_azure_storage",
    ],
    visibility = ["//visibility:public"],
)
