java_library(
    name = "jena_rml",
    srcs = glob([
        "**/*.java",
    ]),
    deps = [
        "//timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/rml:rml",
        "//third_party:org_apache_jena_jena_arq",
        "//third_party:org_apache_jena_jena_core",
    ],
    visibility = ["//visibility:public"],
)
