= Resource sync

== Summary
//tag::summary[]
Timbuctoo can discover and download datasets from remote servers that contain resourcesync descriptions.
//end::summary[]

== Context

=== Client side

The ResourceSync Framework is used to exchange rdf-data with remote quad stores.
Features in this package include:

- nl.knaw.huygens.timbuctoo.remote.rs.xml - marshal and unmarshal sitemap documents to and from java classes
- nl.knaw.huygens.timbuctoo.remote.rs.discover - discover and navigate a remote ResourceSync document tree
- nl.knaw.huygens.timbuctoo.remote.rs.view - render the result of an expedition for json.
- nl/knaw/huygens/timbuctoo/remote/rs/ResourceSyncService.java - central service
- nl/knaw/huygens/timbuctoo/server/endpoints/v2/remote/rs/Discover.java - web service API

=== Server side

- nl.knaw.huygens.timbuctoo.v5.datastores.resourcesync - contains all the classes to build a resource sync structure
- nl.knaw.huygens.timbuctoo.v5.dropwizard.endpoints.ResourceSyncEndpoint - is the REST endpoint that servers the resourcesync files

== Data model

The http://www.openarchives.org/rs/1.1/resourcesync[resource sync specification] describes how various documents interlink in order to describe a set of resources and where the entrypoints should be placed.
In it's simplest form it is just one file containing a directory listing with a predefined name.
This is needed because the HTTP spec itself does not define a "list" command.
Resourcesync is a set of embelishments on the sitemap.xml de-facto standard.
Timbuctoo uses resourcesync to discover datasets at a source and to get the list of files that comprise the dataset.

The document linked above provides the full spec, but we found it convenient to draw a picture of the various documents:

[ditaa]
--
                                     +--------------------+
                                     |                    |
/.well-known/resourcesync  +-------> | Source description |
                                     |                    |
                                     +---------+----------+
                                               |1
                                               |
                                               Vmany
                                      +--------+--------+
                                      |                 |
                                      | Capability list | <--------+ Link header/Link tag
                                      |                 |
                                      +----+---------+--+
                                           |1        |1
                                           |         |
                                           |         V1
                                           |  +=--------------------+
                                           |  |                     |
                                           |  |(Resource index list)|
                                           |  |                     |
                                           |  +------+--------------+
                                           |         |1
                                           |         |
                                           V1        Vmany
                                       +---+-----------+
                                       |               |
                                       | Resource list | <--------+ robots.txt
                                       |               |
                                       +-------+-------+
                                               |many
                                               Vmany
                                        +-------------+
                                        |{d}          |
                                        | Actual file |
                                        |             |
                                        +-------------+


--

The horizontal arrows indicate entrypoints.
If you provide timbuctoo (or another resourcesync destination) with a url it may try to find a link header/link tag, a resourcesync file in the folder .well-known at the root of the server, or a robots.txt.
Each file provides links downwards, optionally they might also provide a link upwards.
A source description contains links to one or more capability lists, each list is considered to contain 1 dataset by timbuctoo.
A capability list will link to one or more files via a resource (index) list.
All files in the resource list are considered to be part of the same dataset.
A capability list may also point to a resource dump and/or changesets, these features are currently not supported and will be ignored.

Walking up the resource chain is also not yet implemented.

So to create a resourcesync capable server for timbuctoo you should:

 1. Put a http://www.openarchives.org/rs/1.0.9/resourcesync#ex_7[source description] at `/.well-known/resourcesync` on your server
 2. Fill it with links to http://www.openarchives.org/rs/1.0.9/resourcesync#ex_6[capability lists] (1 per dataset that you wish to publish)
 3. Fill them with links to http://www.openarchives.org/rs/1.0.9/resourcesync#ex_1[Resource lists]
 4. Fill those with links to the actual data files in one of the supported rdf formats (see below)

You may use the `describedby` mechanism (see http://www.openarchives.org/rs/1.1/resourcesync#DocumentFormats ) to point to documents that describe your datasets. These description documents can be in any format, however, using one of the RDF-formats is recommended. Timbuctoo interprets http://www.openarchives.org/rs/1.1/resourcesync#CapabilityList[capabilitylist's] as description of a dataset. Therefore expects that the metadata of a `capabilitylist` will contain the `describedby` mechanism. This `describedBy` item can either be added to a url in the sourcedescription or to the root item of the `capabilitylist`.

=== Valid resources
Timbuctoo cannot sync every filetype on the internet, only files containing rdf in several of the more well-known serialisation formats.
To indicate the serialisation format you can specify the mimetype in the optional `md` field (meta data field) for each url from the resource list.
Alternatively you can use a file extension to indicate the type of file.
The explicit mimetype overrules the file extension.

The filetypes that we can currently import are:

 * text/turtle (.ttl)
 * application/rdf+xml (.rdf)
 * application/n-triples (.nt)
 * application/ld+json (.jsonld)
 * application/trig (.trig)
 * application/n-quads (.nq)
 * text/n3 (.n3)
 * application/vnd.timbuctoo-rdf.nquads_unified_diff (.nqud)
So we expect an item resource list will look like:

```
...
<url>
    <loc>http://localhost/.well-known/resourcesync/dataset1/resource2.nq</loc>
    <rs:md type="application/n-quads"/> <!-- this line is optional, but can be used to override the extension -->
</url>
...
```

== Making Timbuctoo your resourcesync server
Be default when a file is imported into Timbuctoo that file will be automatically share via the resourceync protocol.
The following url's are important to remember:

- http://localhost:8080/.well-known/resourcesync - this will redirect to the source description
- http://localhost:8080/v5/resourcesync/sourceDescription.xml - the url of the source description, describes all public the data sets in Timbuctoo
- http://localhost:8080/v5/resourcesync/{user name}/{data set name}/capabilityList.xml - describes the capabilities of a specific data set
- http://localhost:8080/v5/resourcesync/{user name}/{data set name}/resourceList.xml - describes the resources (uploaded files) of a data set

== Steps to test the client API
Got to the folder `{timbuctoo-root}/documentation/resourcesyncexample`.
include::../../../../../../../../../../documentation/resourcesyncexample/README.adoc[tags=startup]

- http://localhost:8080/v2.1/remote/rs/discover/listsets?url=http%3A%2F%2Fyour%2Frdf%2Fserver - list the datasets at the remote site
- http://localhost:8080/v2.1/remote/rs/discover/framework?url=http%3A%2F%2Fyour%2Frdf%2Fserver - flat representation of the ResourceSync Framework documents
- http://localhost:8080/v2.1/remote/rs/discover/tree?url=http%3A%2F%2Fyour%2Frdf%2Fserver - hierarchical representation of the ResourceSync Framework documents
N.B. You can use `http%3A%2F%2Flocalhost%3A8080%2Fv5%2Fresourcesync%2FsourceDescription.xml` in stead of `http%3A%2F%2Fyour%2Frdf%2Fserver` to use the same Timbuctoo instance as client and server.

== Working with the ../remote/rs/xml package
When downloading a ResourceSync doument we do not always know whether we find a &lt;sitemapindex&gt; or a &lt;urlset&gt;. The two kinds of document are represented as java classes `Urlset` and `Sitemapindex`, both have a common superclass, `RsRoot`. The class `RsBuilder` in this package will take a variety of input types and produces an Optional of `RsRoot`. If the unmarshal operation succeeded then either one of the methods
`Optional<Urlset> getUrlset()` or `Optional<Sitemapindex> getSitemapindex()` will yield.

The RsBuilder class also has a convenience method for marshaling a `RsRoot` subclass to its xml-representation: `String toXml(RsRoot rsRoot, boolean formattedOutput)`. If needed this class could be extended to marshal to different types: `toXmlString`, `toXmlFile` etc.

To build a ResourceSync document from java, the JAXB-classes can be used and populated with values. However, extensive syntax checking is not done. To build valid ResourceSync documents you still need to consult the documentation.

== Working with the ../remote/rs/discover package
The principle behind the `AbstractUriExplorer` and `Result<?>` classes is agnostic to the ResourceSync Framework. It presents the opportunity to explore any URI and relate it to some kind of response or the absence of it. In case of a response, the response can be converted through some kind of function to some java class, the 'content' of the `Result`. Also any errors while getting the response or during conversion will be stored in the `Result` instance. Not handling errors in this code is natural. The maturity of possible errors will have a cause that is on the remote end. Here we register errors only to report them to end users.

The above abstraction comes together in the `AbstractUriExplorer` method with the signature
``
<T> Result<T> execute(URI uri, Function_WithExceptions<HttpResponse, T, ?> func)
``
Furthermore, the principle that any document on the internet can have incoming links and outgoing links is expressed in the `Result` class with parents (for incoming links) and children (for outgoing links).

The ResourceSync documents on a remote site can be seen as a tree or network; all documents have relations of some type to other documents. With the help of the concrete classes `LinkExplorer` and `RsExplorer` such a network can be explored. The `Expedition` class uses these explorers to test four methods of discovering a remote network of ResourceSync documents. At the moment an Expedition discovers _all_ ResourceSync documents at the remote site, which might be overkill in case we are looking for a particular document and the remote site has substantial amounts of related documents. 

todo:feature[Introduce a Navigator class that is handed through `Expedition.explore` methods up to the `RsExplorer` class and that, having been given a target, knows whether the exploration has to go up, down or sideways through parent and child links in order to reach the target document. The enum `Capability` in the xml package already knows about parent and child relations between the various document types and might be useful in this navigation attempt.]

All results come together in a `ResultIndex`, which is essentially a collection of mappings between URIs and `Result<?>`s. The `ResultIndexPivot` class is a wrapper around such a `ResultIndex` that facilitates data summarizations. Of course the `ResultIndex` itself can be used as a starting point to 'stream' summarizations without intermediate reduce operations. 

== Working with the ../remote/rs/view package

This package has several 'views' on results and result details that are shaped for (one way) Json serialization. Classes that take a `ResultIndex` are marked with the word 'Base': `SetListBase`, `FrameworkBase`, `TreeBase`.  The constructors of these classes take the result detail they are supposed to render and an `Interpreter` which introduces some flexibility on how a detail is rendered. The `Interpreter` and `Interpreters` classes should be extended with whatever interpreters are needed for more sophisticated renderings. Of course in such a case also particular methods in  the views have to be adopted to make use of the interpreter.

== The Discover API
The class `nl.knaw.huygens.timbuctoo.server.endpoints.v2.remote.rs.Discover` handles API calls that enable discovering a remote ResourceSync source.

== What remains to be done

- todo:feature[be able to handle "resource index lists" in discovery and download]
- todo:feature[resourcesync discovery should only request the source description document if you pass it a full url. (It currently also downloads all capability lists)]
- todo:feature[resourcesync discovery walks the up-chain to get to the source description document if you pass a secondary level document (capabilitylist or resourcelist, resource index list)]
- todo:feature[resourcesync discovery returns a list with only the secondary level document if the up-chain cannot be walked]
- todo:task[make resourcesync client available on v5 api]
