java_library(
  name = 'opencsv',
  visibility = ['PUBLIC'],
  exported_deps = [
    ':opencsv_jar'
  ],
)
prebuilt_jar(
  name = 'opencsv_jar',
  binary_jar = ':opencsv_remote_jar',
  deps = [
  ],
  visibility = [
    'PUBLIC'
  ],
)
remote_file(
  out = 'opencsv.jar',
  name = 'opencsv_remote_jar',
  url = 'http://repo.maven.apache.org/maven2/net/sf/opencsv/opencsv/2.3/opencsv-2.3.jar',
  sha1 = 'c23708cdb9e80a144db433e23344a788a1fd6599',
)

