#! /bin/bash

do_start()
{
  echo "starting Timbuctoo"
  runuser -l timbuctoo -c '/data/timbuctoo/app/bin/timbuctoo server /data/timbuctoo/app/conf/config.yaml'
}

get_pid()
{
  echo `pgrep -fx ".*java.*timbuctoo.*"`
}

do_stop()
{
  echo "stopping Timbuctoo"
  
  pid=`get_pid`

  if [ ! "$pid" ]; then
    echo "Timbuctoo is not running"
    return 1;
  else  
    `kill -2 $pid`
    return 0
  fi
}

get_status()
{
   pid=`get_pid`

  if [ "$pid" ]; then
      echo "timbuctoo is running and has pid $pid"
      return 0;
  else
      echo "timbuctoo is not running"
      return 0;
  fi
}

do_restart()
{
  do_stop
  do_start
}

case "$1" in
  start)
    do_start
    ;;
  stop)
    do_stop
    ;;
  status)
    get_status
    ;;
  restart)
    do_restart
    ;;
  *)
    echo "Usage: timbuctoo {start|stop|status|restart}" >&2
    exit 3
    ;;
esac
