package nl.knaw.huygens.timbuctoo.model;

public enum DocumentType {
  UNKNOWN, ANTHOLOGY, ARTICLE, AWARD, CATALOGUE, COMPILATION, DIARY, LETTER, LIST, MONOGRAPH, PERIODICAL,
  PICTURE, PUBLICITY, SHEETMUSIC, THEATERSCRIPT, WORK
}
