java_library(
  name = 'HttpCommand',
  srcs = glob(['src/main/java/**/*.java']),
  deps = [
    "//buckbuild/jars/org/concordion:concordion",
    "//buckbuild/jars/xom:xom",
    "//buckbuild/jars/com/google/guava:guava",
    "//ContractDiff:ContractDiff",
    "//buckbuild/jars/com/fasterxml/jackson/core:jackson-databind",
    "//buckbuild/jars/org/apache/commons:commons-lang3",
    "//buckbuild/jars/org/apache/httpcomponents:httpcore",
    "//buckbuild/jars/javax/ws/rs:javax.ws.rs-api",
  ],
  exported_deps = [
  ],
  visibility = [
    "PUBLIC"
  ]
)
