= Edit mutations

== Context
At the moment of writing, Timbuctoo's GraphQL API has several mutations to edit metadata like facets and summary properties.
But the real data cannot not be edited with the GraphQL API.
This has to be done with the `JSON-LD endpoint` or uploading NQUD-files to the `RDF upload endpoint`.
The problem with the ways mentioned in the last sentence is that both can also change the GraphQL schema of a data set.
A GraphQL edit mutation for each type should protect against unwittingly changing the schema.

== Definition of done
. Mutations for each collection should be added to the GraphQL schema.
. Only users with with `WRITE` permissions should be able to see and use the mutations.
. Timbuctoo generates a provenance file that contains the changes and adds the data to the data set.

== API design
```
...
mutation EditEntity (uri: String! entity: <collectionName>Input!) {
  dataSets {
    <dataSetId> {
      <collectionName>
        edit(uri: $uri entity: $entity) {
          <entityTypeField1>
          <entityTypeField3>
          <entityTypeFieldN>
        }
      }
    }
  }
}
...
input <collectionName>Input {
  additions: <collectionName>PropertiesInput
  deletions: <collectionName>PropertiesInput
  replacements: <collectionName>PropertiesInput
}

input <collectionName>PropertiesInput {
  <entityTypeField1>: PropertyInput
  <entityTypeField2>: PropertyInput
  <entityTypeFieldN>: PropertyInput
}

input PropertyInput {
  type: String!
  value: String!
}
```


== Limitations
* Value fields of the object can be edited.
* Links to objects can be changed.

== Development steps
. Generate the API
. Add a DataFetcher mutation that stores the data
. Hide the API from users without writing permission
. Generate a provenance file of the changes and add the data to the data set
. Add functionality for adding new items to collections
. Add functionality for deleting items from collections

== Links
Organizing mutations: https://medium.freecodecamp.org/organizing-graphql-mutations-653306699f3d
