= Edit mutations

== The problem
At the moment of writing, Timbuctoo's GraphQL API has several mutations to edit metadata like facets and summary properties.
But the real data cannot not be edited with the GraphQL API.
This has to be done with the `JSON-LD endpoint` or uploading NQUD-files to the `RDF upload endpoint`.
The problem with the ways mentioned in the last sentence is that both can also change the GraphQL schema of a data set.
A GraphQL edit mutation for each type should protect against unwittingly changing the schema.


=== Possible operations
Possible operations the user might execute on the data:

. Change single valued value or link properties (i.e. the birth date of a person or the birthplace of a person)
.. Overwrite the current value
.. Clear the current value
. Change multi valued value or link properties (i.e. the first names of a person or places a person lived in)
.. Add one or more items to the list
.. Delete one or more items from the list
.. Overwrite the complete list with a new value
.. Clear the complete list
. For all above points there should be an optional check if the data wasn't changed in the meantime.


=== Validation
A mutation on the data might produce an "invalid" dataset. We can have vaildation on

. An entity against the schema (Person's may only have 1 birthdate, it must be EDTF)
. A value against the type (An xsd:integer may only be [0-9]+)
. An entity against some local rules (each Person must have a "name")
. An entity against some global rules (a person may not have the same BSN as another person entity, all person entities must have a birthdate within the early modern period)

=== Provenance
. A user should be able to add provenance information such as where a piece of information is retrieved from.
. Timbuctoo might record some provenance (user, change date, etc.) automatically.

== Definition of done
. Mutations for each collection should be added to the GraphQL schema. (point 1 and 2 of <<Possible operations>>)
. Non of the mutations can change the schema of the data set. (see <<Validation>>)
.. No new properties can be introduced.
.. No new types can be added to existing properties.
.. Single valued properties cannot become multi valued.
. Only users with with `WRITE` permissions should be able to see and use the mutations.
. Timbuctoo generates a provenance file that contains the changes and adds the data to the data set.
. A user should be able to add provenance.

== Design

=== Provenance schema

----





                                                    "Timbuctoo change"                              "Reading book"                     "A book"
                                                          ^                                              ^                                ^
                                                          |   schema:description                         | schema:description             | schema:title
                                                          |                                              |                                |
                                                          |                                              |                                |
+---------------------+   tim:hasProvenace    +-----------+------+     prov:informedBy         +---------+-----------+  prov:used +-------+-----------+
|                     |                       |                  |                             |                     |            |                   |
|  tim:ChangeLog      +---------------------->+ prov:Activity    +---------------------------->+ prov:Activity       +----------->+ prov:Entity       |
|                     |                       |                  |                             |                     |            |                   |
+---------------------+                       +------------------+                             +---------------------+            +-------------------+
                                                       |                                       |
                                                       |                                       |
                                                       | prov:associatedWith                   |
                                                       |                                       |  prov:associatedWith
                                                       v                                       |
                                              +--------+---------+<----------------------------+
                                              |                  |
                                              | prov:Agent       |
                                              |                  |
                                              +-------+----------+
                                                      |
                                                      | tim:user
                                                      v
                                                 "<user id>"



----

=== GraphQL

==== Example
----
mutation EditEntity (uri: String! entity: <collectionName>Input!) {
  dataSets {
    <dataSetId> {
      <collectionName>Operations {
        edit(uri: $uri entity: $entity) {
          <entityTypeField1> {
            value
          }
          <entityTypeField3> {
            value
          }
          <entityTypeFieldN> {
            value
          }
        }
      }
    }
  }
}
----

==== Schema
----
...
type <collectionName>Operations {
  edit(uri: String! entity: <collectionName>Input!): <collectionName>
}

input <collectionName>Input {
  additions: <collectionName>PropertiesInput
  deletions: <collectionName>PropertiesInput
  replacements: <collectionName>PropertiesInput
  provenance: ProvenanceInput
}

input <collectionName>PropertiesInput {
  <entityTypeField1>: PropertyInput # Single value / link property
  <entityTypeField2>: [PropertyInput!] # List property for values or links
  <entityTypeFieldN>: PropertyInput # Single value / link property
}

input PropertyInput {
  type: String!
  value: String!
}

input ProvenanceInput {
  informedBy: InformedByInput!
}

input InformedByFromInput {
  entity: ProvenanceEntity!
  activity: String! # description of the activity
}

input ProvenanceEntity {
  uri: String # will be generated when absent
  title: String!
}
...
----

=== Java
The schema will be generated by the `DerivedSchemaGenerator`.

----
+------------------------+           +------------------------+          +---------------------+
|                        |           |                        |          |                     |
| DerivedSchemaGenerator +----------^+ DerivedSchemaContainer +---------^+ TypeSchemaGenerator |
|                        |           |                        |          |                     |
+------------------------+           +------------------------+          +-----+-----------+---+
                                                                               ^           ^
                                                                               |           |
                                                          +--------------------+-----+  +--+------------------------+
                                                          |                          |  |                           |
                                                          | ValueTypeSchemaGenerator |  | ObjectTypeSchemaGenerator |
                                                          |                          |  |                           |
                                                          +--------------------------+  ++--------+-------------+---+
                                                                                         ^        ^             ^
                                                                                         |        |             |
                                                                                         |        |             +---------------------+
                                                                                         |        |                                   |
                                                              +--------------------------++  +----+---------------------+  +----------+--------------------+
                                                              |                           |  |                          |  |                               |
                                                              | QueryTypeSchemaGenerator  |  | InputTypeSchemaGenerator |  | OperationsTypeSchemaGenerator |
                                                              |                           |  |                          |  |                               |
                                                              +---------------------------+  +--------------------------+  +-------------------------------+

----

* `DerivedSchemaGenerator` is the same class as the current `DerivedSchemaTypeGenerator`.
* `DerivedSchemaContainer` will be simplified, because most of the functionality will be moved to the `TypeSchemaGenerators`.
* `TypeSchemaGenerator` is an interface for creating GraphQL schema's from RDF types.
** `ValueTypeSchemaGenerator` will generate a schema for value types.
** `ObjectTypeSchemaGenerator` will generate a schema for object types (types with properties).
*** `QueryTypeSchemaGenerator` will create the schema for types used in the GraphQL queries.
*** `OperationsTypeSchemaGenerator` will create the schema for the types that contain the type specific mutations,
*** `InputTypeSchemaGenerator` will create the schema for types that are used in the mutations of the `OperationsTypeSchemaGenerator`.


== Limitations
* Only value fields of the object can be edited. (like person names, birth date)
* Only links to objects can be changed. (birthplace, places lived in)

So no values of linked objects can be edited.

== Development steps
. Generate the API
. Add a DataFetcher mutation that stores the data
. Hide the API from users without writing permission
. Generate a provenance file of the changes and add the data to the data set
. Add functionality for adding new items to collections
. Add functionality for deleting items from collections

== Links
Organizing mutations: https://medium.freecodecamp.org/organizing-graphql-mutations-653306699f3d
