= Make the tabular file list schema static

== The problem
=== Schema is hard to customize
A large part of the current GraphQL schema is dynamically generated.
Some generated parts like the data sets contain default recurring schema parts like _metadata_.
Not all these default recurring parts are generated statically.

The part that is causing problems is the link be tabular files and their raw collections.
At this moment there is a big difference between _csv_- and _excel_-files.

*example of an uploaded csv file*
```
...
http___timbuctoo_huygens_knaw_nl_static_v5_types_tabularFileList {
  items {
    tim_hasCollection {
      ... on u33707283d426f900d4d33707283d426f900d4d0d__voc_http___example_org_datasets_u33707283d426f900d4d33707283d426f900d4d0d_voc_rawData_a8afae5a_542a_47b8_aca9_bf3aa89510aa_vocopvarenden0_50000_csv_collections_1type {
        uri
        rdfs_label {
          value
        }
        tim_hasPropertyList {
          items {
            rdfs_label {
              value
            }
          }
        }
      }
    }
  }
}
...
```

*example of an uploaded excel file with two sheets*
```
...
http___timbuctoo_huygens_knaw_nl_static_v5_types_tabularFileList {
  items {
    tim_hasCollectionList {
      items {
        ... on u33707283d426f900d4d33707283d426f900d4d0d__bioport3_http___timbuctoo_huygens_knaw_nl_static_v5_types_tabularCollection {
          uri
          rdfs_label {
            value
          }
          tim_hasPropertyList {
            items {
              rdfs_label {
                value
              }
            }
          }
        }
      }
    }
  }
}
...
```

== Expected result
Each time the schema for a `tabularFileList` is created it should look like the schema below.
```
...
tabularFileList {
  items {
    fileName { value }
    hasCollectionList {
      items {
        name {
          value
        }
        hasPropertyList {
          items {
            name {
              value
            }
          }
        }
      }
    }
  }
}
...
```

== The solution
* Change `schema.graphql` to add a structure for `tabularFileList`.
** Make sure the property does not contain any underscores in the name, because all the generated properties contain at least one underscore,
* Create a `DataFetcher` for `tabularFileList`.
* Change `RootQuery` to add the `tabularFileList` and its DataFetcher.

== Possible improvements
* Make the schema configurable in the Timbuctoo config.

== To do after the fix
. Make the timbuctoo-mapping tool support excel.

