= Add support for users to be able to add alternative redirection services (in addition to 'handle') to Timbuctoo

== Problem:
Currently, Timbuctoo only supports the Handle redirection service. It's not easy for Timbuctoo users to integrate other
redirection services as the configuration for the Handle redirection is hard-coded into Timbuctoo.

== Result:
The hard-coded integration of Handle redirection service will be removed. Redirection service will now have to be
specified instead in the Timbuctoo configuration. The users will be able to write implementations for their desired
redirection service and configure Timbuctoo to use a new redirection service.

The user will be able to do so as follows:

=== Steps to add a desired reduction service to Timbuctoo and configure Timbuctoo to use it:
- In the example_config.yaml file, change  the "redirectionService" property and child properties values to your
new implementation.

For example, Timbuctoo default:
----
redirectionService:
    "@class": nl.knaw.huygens.timbuctoo.v5.redirectionService.HandleRedirectionFactory
    configFile: ${timbuctoo_dataPath}/configs/redirectionService/handleConfig.yaml
----

can be changed to use your new Bitly implementation as:
----
redirectionService:
    "@class": nl.knaw.huygens.timbuctoo.v5.redirectionService.BitlyUrlCreatorFactory
    configFile: ${timbuctoo_dataPath}/configs/redirectionService/bitlyConfig.yaml
----

"configFile" above should point to the location of a file containing the configuration information necessary to build
the redirection service. This can include information such as API authentication key, user information, etc. The factory
class mentioned above should then be able to use the specified information to build a redirection service.

The factory class should extend the RedirectionFactory interface (new) and thus implement the createRedirectionService
function to create the new redirection service.

This new implementation class for the redirection service should include the "init" and "add" functions.


== Approach:

- The initial step will be to add support to one more redirection service as a test case, in addition to Handler. Bit.ly
was chosen as the service as it has a Java library available.

NOTE: We are using Bit.ly for testing purposes to make sure that the new way of setting up redirection services works
with Timbuctoo. Bit.ly will **not** be available as an option in production instances.

- Currently, handleAdder, specific to the handle service, is added directly to Timbuctoo. We need to change this so that
the user can configure any implementation of the PersistenceUrlCreator in place of the handleAdder.

- A RedirectionFactory interface will be created that will have a "createRedirectionService" method. This method will
have to be implemented for each redirection service.

- Current handle service will be refactored to meet the above specification.

- A new class BitlyUrlCreatorFactory that implements the RedirectionFactory will be added.

- This factory class will have the "createRedirectionService" method to build the Bitly redirection service using the
configuration set in the specified file (specified in Timbuctoo yaml configuration).

- This BitlyUrlCreator will use the [Bit.ly Java API client](https://github.com/stackmagic/bitly-api-client)

- The Bit.ly client will be used to call the Java client library as follows:

----
ShortenResponse respShort = new ShortenRequestBuilder("... the access token ...") //
    .setLongUrl("https://example-timbuctoo-url/") //
    .call();
----

