= Add support for users to be able to add alternative redirection services (in addition to 'handle') to Timbuctoo

== Problem:
Currently, Timbuctoo only supports the Handle redirection service. It's not easy for Timbuctoo users to integrate other
redirection services as the configuration for the Handle redirection is hard-coded into Timbuctoo.

== Result:
The hard-coded integration of Handle redirection service will be removed. Redirection service will now have to be
specified instead in the Timbuctoo configuration. The users will be able to write implementations for their desired
redirection service and configure Timbuctoo to use a new redirection service.

The user will be able to do so as follows:

=== Steps to add a desired redirection service to Timbuctoo and configure Timbuctoo to use it:
- In the example_config.yaml file, change  the "redirectionService" property and child properties values to your
new implementation.

For example, Timbuctoo default:
----
redirectionService:
    "@class": nl.knaw.huygens.timbuctoo.v5.redirectionService.HandleRedirectionServiceFactory
    useDummy: yes #set to "no" to connect to a real handle server
    #  privateKeyFile:
    #  cypher:
    #  namingAuthority:
    #  prefix:
----

can be changed to use your new Bitly implementation as:
----
redirectionService:
    "@class": nl.knaw.huygens.timbuctoo.v5.redirectionService.BitlyUrlCreatorServiceFactory
    user: Example User
    authKey: ${BITLY_AUTH_KEY}
    # ...
----

NOTE: It's the user's responsibility to make sure that the configuration parameters required by the the implementation
are added to the configuration file.

The factory class mentioned above should then be able to use the specified information to build a redirection service.

The factory class should implement the RedirectionServiceFactory interface (new) and thus implement the
"makeRedirectionService" function to create the new redirection service.

This new implementation class for the redirection service should implement the RedirectionService interface and thus
implement the "add" function.


== Approach:

- The initial step will be to add support to one more redirection service as a test case, in addition to Handler. Bit.ly
was chosen as the service as it has a Java library available.

NOTE: We are using Bit.ly for testing purposes to make sure that the new way of setting up redirection services works
with Timbuctoo. Bit.ly will **not** be available as an option in production instances.

- Currently, handleAdder, specific to the handle service, is added directly to Timbuctoo. We need to change this so that
the user can configure any implementation of the PersistenceUrlCreator in place of the handleAdder.

- A RedirectionServiceFactory interface will be created that will be structured as follows:

----
public interface RedirectionServiceFactory {
    RedirectionService makeRedirectionService();
}
----

- A RedirectionService interface will also be created and structured as follows:

----
public interface RedirectionService {
    void add(URI uriToRedirectTo, EntityLookup entityLookup);
}
----

- Current handle service will be refactored to meet the above specification.

This means we will now have a HandleServiceFactory that extends the RedirectionServiceFactory:
----
public class HandleServiceFactory implements RedirectionServiceFactory {
    @JsonCreator
    public HandleServiceFactory(@JsonProperty("useDummy") boolean useDummy,
        @JsonProperty("privateKeyFile") String privateKeyFile, ...) {
        ...
    }

    RedirectionService makeRedirectionService() {
        ...
    }
}
----

Here, makeRedirectionService will return a:
----
public class HandleService implements RedirectionService {
    void add(URI uriToRedirectTo, EntityLookup entityLookup){
        ...
    }
}
----

- Similarly, we will implement the RedirectionServiceFactory and RedirectionService classes for Bit.ly service (for test
purposes) as follows:

This means we will now have a BitlyServiceFactory that extends the RedirectionServiceFactory:
----
public class BitlyServiceFactory implements RedirectionServiceFactory {
    @JsonCreator
    public HandleServiceFactory(@JsonProperty("user") String user,
        @JsonProperty("authKey") String authKey, ...) {
        ...
    }

    RedirectionService makeRedirectionService() {
        ...
    }
}
----

Here, makeRedirectionService will return a:
----
public class BitlyService implements RedirectionService {
    void add(URI uriToRedirectTo, EntityLookup entityLookup){
        ...
    }
}
----

- This Bit.lyService will use the [Bit.ly Java API client](https://github.com/stackmagic/bitly-api-client)

- The Bit.ly client will be used to call the Java client library as follows:

----
ShortenResponse respShort = new ShortenRequestBuilder("... the access token ...") //
    .setLongUrl("https://example-timbuctoo-url/") //
    .call();
----

