java_library(
    name = "twitterexample",
    srcs = glob([
        "**/*.java",
    ]),
    deps = [
      "//timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/util",
      "//timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5",
      "//third_party:org_twitter4j_twitter4j_core",
      "//third_party:org_apache_httpcomponents_httpclient",
      "//third_party:javax_ws_rs_javax_ws_rs_api",
    ],
    visibility = ["//visibility:public"],
)
