= OAuth Authentication Implementation in Timbuctoo

.How to add an OAuth client implementation in Timbuctoo
* Implement the UserValidator interface (v5/security/userValidator):
** The "getUserFromAccessToken" method should take a String access token
and send it to the desired OAuth Security Server for verification.
** When you receive the verified user information back from the
security server you should use it to construct a Timbuctoo User object.
** You can do so by calling the method User.create which accepts a user_name,
 user_persistent_id and user_id as arguments.
** You should have the method return the above User object or
an Optional.empty() if one is not constructed.
** The 'getUserFromId' method should be implemented in the same way except
now you are using a known userId to get user information from your
security server (instead of the access token).
* Set-up security configuration to use the new UserValidator:
** Implement the SecurityFactory interface (v5/security/SecurityFactory)
*** Set up a new instance of your UserValidator in the constructor
*** Have the function 'getUserValidator' return this UserValidator
*** Have the functions 'getPermissionFetcher' and 'getHealthChecks' either use
Timbuctoo's existing 'OldStyleSecurityFactory' implementation or write new ones.
** Implement the SecurityFactoryConfiguration interface
*** You can extend the "OldStyleSecurityFactoryConfiguration" to do this.
*** Override the method "createNewSecurityFactory" to return the new SecurityFactory
implementation that you created.
* Inject the Validator into Timbuctoo:
** Open up example_config.yaml and set the "securityConfiguration" class to point
to your new security factory configuration. Eg:
"@class": nl.knaw.huygens.timbuctoo.v5.security.oauthexample.NewOauthSecurityFactoryConfiguration

= Testing the OAuth Authentication Implementation
* Run Timbuctoo
* Use client web application to Login to the OAuth server and obtain the accessToken and secret.
* send a GET request to "<timbuctoo>/v2.1/system/users/me" with the authorization header
value as the accessToken concatenated with the token secret and separated by an underscore i.e.
<accessToken>_<tokenSecret>
* you should receive back the User object including displayName, persistentId and Id.


== Example Twitter Implementation
* An example Twitter implementation (that uses the Twitter4j library) has been
provided for demonstration and testing purposes. This example implementation will let you authenticate a
Timbuctoo user by using their Twitter credentials.
** The implementation is available at:
 "<timbuctoo_root>/timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/security/twitterexample/"
** To use the example Twitter implementation, open up example_config.yaml and set the "securityConfiguration" class to point
  to it:
  "@class": nl.knaw.huygens.timbuctoo.v5.security.twitterexample.TwitterSecurityFactoryConfiguration
