java_library(
  name = 'junit',
  visibility = ['PUBLIC'],
  exported_deps = [
    ':junit_jar'
  ],
)
prebuilt_jar(
  name = 'junit_jar',
  binary_jar = ':junit_remote_jar',
  deps = [
    '//buckbuild/jars/org/hamcrest:hamcrest-core',
  ],
  visibility = [
    'PUBLIC'
  ],
)
remote_file(
  out = 'junit.jar',
  name = 'junit_remote_jar',
  url = 'http://repo.maven.apache.org/maven2/junit/junit/4.12/junit-4.12.jar',
  sha1 = '2973d150c0dc1fefe998f834810d68f278ea58ec',
)

