java_library(
  name = 'security-client-agnostic',
  srcs = glob(['src/main/java/**/*.java']),
  deps = [
    "//buckbuild/jars/com/google/guava:guava",
    "//buckbuild/jars/nl/knaw/huygens:security-core",
  ],
  exported_deps = [
  ],
  visibility = [
    "PUBLIC"
  ]
)
