java_library(
    name = "security-client-agnostic",
    srcs = glob([
      "src/main/java/**/*.java",
    ]),
    resources = glob([
      "src/main/resources/**/*",
    ]),
    deps = [
      "//third_party:com_google_guava_guava",
      "//third_party:nl_knaw_huygens_security_core",
    ],
    visibility = ["//visibility:public"],
)
