package nl.knaw.huygens.timbuctoo.v5.security.dto;

public enum Permission {
  CREATE, DELETE, WRITE, READ, PUBLISH_DATASET, REMOVE_DATASET, EDIT_COLLECTION_METADATA, EDIT_DATASET_METADATA,
  EXTEND_SCHEMA, CONFIG_INDEX, CHANGE_SUMMARYPROPS, CONFIG_VIEW, IMPORT_RESOURCESYNC, UPDATE_RESOURCESYNC,
  READ_IMPORT_STATUS, SET_CUSTOM_PROV, IMPORT_DATA
}
