= GraphQL instructions for editing Metadata information in a Timbuctoo DataSet

== SetDataSetMetadata mutation
You can set or update the metadata information for any dataset in Timbuctoo by using the SetDataSetMetadata mutation.

The "setDataSetMetadata" mutation accepts a "dataSetId" parameter and a "metadata" parameter. The "dataSetId" is the
Timbuctoo dataSetId (<user_id>__<dataSet_name> format) for the dataSet whose metadata you want to set or edit. The
metadata is an object containing the values for the dataSet metadata that you want to edit.

Example of a metadata Object:

----
"metadata":{
    "title": "<Title>",
    "discription": "<description>",
    "imageUrl": "<url link to image>",
    "owner": {"name":"<owner name>", "email":"<owner email>"},
    "contact": {"name":"<contact name>", "email":"<contact email>"},
    "provenanceInfo" : {"title":"<title>", "body":"<provenance info>"},
    "license" : {"uri":"license uri"}
}
----


Example query:

----
mutation setMetadata($dataSet:String!, $metadata:DataSetMetadataInput!){
  setDataSetMetadata(dataSetId:$dataSet,metadata:$metadata){
      title{value}
      description{value}
      contact{name{value} email{value}}
  }
}
----

Example query variables (for above query):

----
{
  "dataSet": "testuser__testdataset",
  "metadata": {
    "title": "Test",
    "description": "This is a test description"
    "contact": {"name":"Contact Person", "email": "contactperson@test.com"}
  }
}
----

NOTE: The metadata fields that you omit from your 'setDataSetMetadata" query will have the same values as before the
query.
