= GraphQL instructions for Timbuctoo ResourceSync discover, import and update

== Discover Query
You can do a resource sync discover request by using the "discoverResourceSync" query that accepts a "url" parameter.
The url should be for the resource sync source. Optionally, you can also include a "authorization" token in your query.
This is necessary when the remote source is protected by OAuth or SimpleAuth.

Example:

----
discoverResourceSync(url: "http://example.org/.well-known/resourcesync",
  authorization: "<Auth header>") {
    location,
    description,
    license,
    title
  }
----

The query will return location, description, license and the title of the found resource.

== Import Query
You can do a resource sync import by using the "resourceSyncImport" mutation. You will have to provide a capability list
 uri ("capabilityListUri" param). This can be obtained from the above discover query. You also need to
 provide the "dataSetName" parameter which is the name of the dataSet that is to be created from the imported data.
 In cases where there are more than one dataSet file in the remote source, you'll have to provide an extra
 "userSpecifiedDataSet" param to let Timbuctoo know which dataSet to import.
 Optionally, you can also include a "authorization" token in your query. This is necessary when the remote source
 is protected by OAuth or SimpleAuth.

 Example 1:
 ----
 mutation resourceSyncImport {
   resourceSyncImport(dataSetName: "testdataset",
     capabilityListUri: "http://example.org/path/to/capabilitylist.xml") {
     importedFiles,
     ignoredFiles
   }
 }
 ----

 Example 2 (with authorization and user specified dataset):
 ----
 mutation resourceSyncImport2 {
   resourceSyncImport(dataSetName: "testdataset2",
     capabilityListUri: "http://example.org/path/to/capabilitylist.xml",
     userSpecifiedDataSet:"http://example.org/path/to/file_to_import.nq",
     authorization:"<Auth header>") {
     importedFiles,
     ignoredFiles
   }
 }
 ----

 The query will return a list of imported files and ignored files.

== Update Query
You can update a dataset previously imported using ResourceSync import by using the "resourceSyncUpdate" mutation.
You will need to  provide the "dataSetId" parameter which is the id of the dataSet that is to be updated.
Optionally, you can also include a "authorization" token in your query. This is necessary when the remote source
is protected by OAuth or SimpleAuth.

Example:

----
mutation resourceSyncUpdate {
  resourceSyncUpdate(dataSetId:"testdataset2i",
  authorization: "<Auth header>"){
    importedFiles,
    ignoredFiles
  }
}
----

 The query will return a list of imported files and ignored files.
