== Uploading rdf by hand

=== 1. Logging in
To upload an rdf file, you must first retrieve an ssid.
The easiest way to do so is to go to the graphiql interface (which is available on the timbuctoo url, e.g. http://data.anansi.clariah.nl ) and press the Login button (top left)
After you click it, you will be redirected a few times and eventually will be redirected back.

* You can get you session id (HSID) now by looking at the url and finding the `hsid` argument (e.g. `?hsid=aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa`)

You can then execute the following query to verify that you're actually logged in:

```graphql
{
  aboutMe {
    id
    canCreateDataSet
  }
}
```

* If your id is `null` you are not properly logged in.
* If canCreateDataSet is `false` but your id is not `null` then this timbuctoo instance does not allow you to create your own datasets and you should make sure you have access to an existing dataset were you have ADMIN rights.

=== 2. Uploading the rdf

To upload rdf you generate a HTTP multipart POST request that contains the file and some metadata.
In curl it would look like:

```sh
TIMBUCTOO_URI= #here you put the uri to timbuctoo, e.g. https://data.anansi.clariah.nl
USERID= #here you put the ID of the user that owns the dataset. If you are uploading to your own dataset you put the id here that you got back from the graphql query above.
HSID= # the session id you got from the url bar
DATASETNAME= #whatever you want to call your dataset. This name must be all lowercase or numbers (i.e. [a-z0-9], may contain underscores, but at most one consecutive one and must start with a letter (i.e. [a-z])
FILE= #The path to the file
curl --request POST \
  --url '${TIMBUCTOO_URI}/u${USERID}/${DATASETNAME}/upload/rdf?forceCreation=true' \
  --header 'Content-encoding: gzip' \
  --header 'authorization: ${HSID}' \
  --header 'content-type: multipart/form-data; boundary=---011000010111000001101001' \
  --form encoding=UTF-8 \
  --form file=@${FILE} \
  --form fileMimeTypeOverride=text/turl
```

To check the upload progress you can execute the following graphql command

```graphql
{
  dataSets {
    uUSERID__DATASETNAME { #Replace userid and datasetname with the values you specified at the curl command
      metadata {
        currentImportStatus {
          elapsedTime
          active
          messages
        }
      }
    }
  }
}
```

=== 3. Uploading an rdf patch

To upload an rdf patch you simply specify application/vnd.timbuctoo-rdf.nquads_unified_diff as the mimetype.
In curl it would look the same as the above command, but you replace `text/turtle` with `application/vnd.timbuctoo-rdf.nquads_unified_diff`
